default: &default
  adapter: mysql2
  encoding: utf8
  username: hive
  password: letmein
  hos: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails-api-user_development


test:
  <<: *default
  database: rails-api-user_test


production:
  <<: *default
  database: rails-api-user_production
  username: rails-api-user
  password: <%= ENV['RAILS-API-USER_DATABASE_PASSWORD'] %>
